// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Logger.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Logger.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompLogger__Logger__sendMessage_name = "sendMessage";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompLogger::upCast(::IceProxy::RoboCompLogger::Logger* p) { return p; }

void
::IceProxy::RoboCompLogger::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompLogger::Logger>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompLogger::Logger;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompLogger::Logger::sendMessage(const ::RoboCompLogger::LogMessage& m, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompLogger__Logger__sendMessage_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompLogger::Logger* __del = dynamic_cast< ::IceDelegate::RoboCompLogger::Logger*>(__delBase.get());
            __del->sendMessage(m, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompLogger::Logger::begin_sendMessage(const ::RoboCompLogger::LogMessage& m, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompLogger__Logger__sendMessage_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompLogger__Logger__sendMessage_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(m);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompLogger::Logger::end_sendMessage(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompLogger__Logger__sendMessage_name);
}

const ::std::string&
IceProxy::RoboCompLogger::Logger::ice_staticId()
{
    return ::RoboCompLogger::Logger::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompLogger::Logger::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompLogger::Logger);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompLogger::Logger::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompLogger::Logger);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompLogger::Logger::__newInstance() const
{
    return new Logger;
}

void
IceDelegateM::RoboCompLogger::Logger::sendMessage(const ::RoboCompLogger::LogMessage& m, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompLogger__Logger__sendMessage_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(m);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::RoboCompLogger::Logger::sendMessage(const ::RoboCompLogger::LogMessage& m, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompLogger::LogMessage& __p_m, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_m(__p_m)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompLogger::Logger* servant = dynamic_cast< ::RoboCompLogger::Logger*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->sendMessage(_m_m, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompLogger::LogMessage& _m_m;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompLogger__Logger__sendMessage_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(m, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* RoboCompLogger::upCast(::RoboCompLogger::Logger* p) { return p; }

namespace
{
const ::std::string __RoboCompLogger__Logger_ids[2] =
{
    "::Ice::Object",
    "::RoboCompLogger::Logger"
};

}

bool
RoboCompLogger::Logger::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompLogger__Logger_ids, __RoboCompLogger__Logger_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompLogger::Logger::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompLogger__Logger_ids[0], &__RoboCompLogger__Logger_ids[2]);
}

const ::std::string&
RoboCompLogger::Logger::ice_id(const ::Ice::Current&) const
{
    return __RoboCompLogger__Logger_ids[1];
}

const ::std::string&
RoboCompLogger::Logger::ice_staticId()
{
    return __RoboCompLogger__Logger_ids[1];
}

::Ice::DispatchStatus
RoboCompLogger::Logger::___sendMessage(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompLogger::LogMessage m;
    __is->read(m);
    __inS.endReadParams();
    sendMessage(m, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompLogger__Logger_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sendMessage"
};

}

::Ice::DispatchStatus
RoboCompLogger::Logger::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompLogger__Logger_all, __RoboCompLogger__Logger_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompLogger__Logger_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___sendMessage(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompLogger::Logger::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompLogger::Logger::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompLogger::__patch(LoggerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompLogger::LoggerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompLogger::Logger::ice_staticId(), v);
    }
}
